language: node_js
before_install:
  - npm install -g grunt grunt-cli
node_js:
  - "0.10"
script:
  - grunt travis
notifications:
  slack:
    masuilab:p4zvcihWTFLz1KwJXYGwJgeZ
env:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=7BPLqS4aRiqcMZ6MiNcMbBh49fNDbO9Vd
