language: node_js
node_js:
  - "0.10"
script:
  - ./node_modules/grunt-cli/bin/grunt travis
notifications:
  slack:
    masuilab:p4zvcihWTFLz1KwJXYGwJgeZ
services: mongodb
env:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=7BPLqS4aRiqcMZ6MiNcMbBh49fNDbO9Vd
